<#
.SYNOPSIS
    One-time setup for the CENTRAL (cross-server) database: starts the
    container, waits for it, writes config\central_dbconfig_admin.txt with
    real credentials, and applies SQL\migrate-central\*.sql.
    Safe to re-run -- migrations are idempotent (CREATE TABLE IF NOT EXISTS),
    same as db_setup.ps1's own local-DB migrations.

.DESCRIPTION
    The central-DB counterpart to db_setup.ps1, same shape, adapted for a
    separate database that may be shared across multiple servers rather than
    owned by just this one:

      - Starts "central-db" (docker-compose.yml), NOT "db" -- separate
        container, port (13306), and volume from this server's own local
        database. Running this never touches the local one.
      - Applies migrations via db_central_update.ps1 (the same simple
        force-reapply-idempotent-SQL approach db_update.ps1 already uses for
        the local DB) rather than Flyway -- one migration mechanism for the
        one (currently small) central schema, not two different ones to
        keep straight.
      - Writes the ADMIN-tier credentials file
        (config\central_dbconfig_admin.txt), not the per-server RUNTIME one
        (config\central_dbconfig.txt) -- this container's root login can
        alter the schema; individual servers should never be handed that.
        Authorize actual servers afterward with db_central_add_server.ps1,
        which creates THEM a separate, deliberately limited login.
      - Enables CENTRAL_SQL_ENABLED in config\config.txt, but deliberately
        does NOT set CENTRAL_SERVER_ID -- that has to be unique across every
        server sharing this database, which is a real decision only you can
        make, not something safe to default.

    Only meaningful if you're actually hosting the shared central database
    on THIS machine -- either because this is your real designated central
    host, or you're testing db_central_*.ps1 locally. If the real central
    database lives elsewhere, you don't need this at all: just fill in
    config\central_dbconfig.txt with the credentials you were given and
    enable CENTRAL_SQL_ENABLED.

.PREREQUISITES
    Docker Desktop must be installed and running.
#>

$ErrorActionPreference = "Stop"

$Root = Split-Path (Split-Path $PSScriptRoot -Parent) -Parent

# ── 1. Verify Docker is available ────────────────────────────────────────────

Write-Host "Checking Docker..." -ForegroundColor Cyan
try {
    docker info 2>&1 | Out-Null
} catch {
    Write-Error "Docker is not running or not installed. Install Docker Desktop and start it, then re-run this script."
    exit 1
}
Write-Host "Docker OK." -ForegroundColor Green

# ── 2. Start the central database container ──────────────────────────────────

Write-Host "`nStarting central database container..." -ForegroundColor Cyan
Set-Location $Root
docker compose up -d central-db

# ── 3. Wait for MariaDB to accept connections (up to 60 s) ───────────────────

Write-Host "Waiting for central database to be ready..." -ForegroundColor Cyan
$attempts = 0
$ready    = $false
while ($attempts -lt 30) {
    Start-Sleep -Seconds 2
    try {
        docker exec aurora-central-db mariadb-admin ping -u root -paurora_central_root 2>&1 | Out-Null
        if ($LASTEXITCODE -eq 0) {
            $ready = $true
            break
        }
    } catch {
        # Server not ready yet -- keep waiting
    }
    $attempts++
    Write-Host "  ...still waiting ($($attempts * 2)s)" -ForegroundColor DarkGray
}

if (-not $ready) {
    Write-Error "Central database did not become ready within 60 seconds. Check 'docker logs aurora-central-db'."
    exit 1
}
Write-Host "Central database is ready." -ForegroundColor Green

# ── 4. Write config/central_dbconfig_admin.txt ───────────────────────────────

Write-Host "`nWriting config/central_dbconfig_admin.txt..." -ForegroundColor Cyan
$configDir = Join-Path $Root "config"
if (-not (Test-Path $configDir)) {
    New-Item -ItemType Directory $configDir | Out-Null
}

$adminConfigLines = @(
    "# Central database ADMIN credentials -- generated by db_central_setup.ps1",
    "# Used only by db_central_update.ps1 / db_central_add_server.ps1 /",
    "# db_central_remove_server.ps1. NEVER hand this file to an authorized",
    "# server -- servers get their own limited login via db_central_add_server.ps1.",
    "",
    "ADDRESS localhost",
    "PORT 13306",
    "DATABASE aurora_central",
    "LOGIN root",
    "PASSWORD aurora_central_root"
)
Set-Content (Join-Path $configDir "central_dbconfig_admin.txt") -Value $adminConfigLines -Encoding UTF8
Write-Host "central_dbconfig_admin.txt written." -ForegroundColor Green

# ── 5. Apply central migrations ───────────────────────────────────────────────

Write-Host "`nApplying central database migrations..." -ForegroundColor Cyan
& "$PSScriptRoot\db_central_update.ps1"
if ($LASTEXITCODE -ne 0) {
    Write-Error "Central migration failed. Check output above."
    exit 1
}

# ── 6. Enable CENTRAL_SQL_ENABLED in config/config.txt ───────────────────────

$configTxt = Join-Path $configDir "config.txt"
if (Test-Path $configTxt) {
    Write-Host "Enabling CENTRAL_SQL_ENABLED in config/config.txt..." -ForegroundColor Cyan
    $content = Get-Content $configTxt -Raw
    $updated = $content -replace '(?m)^#+\s*CENTRAL_SQL_ENABLED', 'CENTRAL_SQL_ENABLED'
    if ($updated -eq $content -and $content -notmatch '(?m)^CENTRAL_SQL_ENABLED') {
        $updated = $content + "`nCENTRAL_SQL_ENABLED`n"
    }
    Set-Content $configTxt $updated -Encoding UTF8
    Write-Host "CENTRAL_SQL_ENABLED set." -ForegroundColor Green
    Write-Host "CENTRAL_SERVER_ID NOT set -- it must be unique across every server sharing" -ForegroundColor Yellow
    Write-Host "this database, which only you can decide. Set it yourself in config.txt." -ForegroundColor Yellow
} else {
    Write-Host "config/config.txt not found -- copy config/example/config.txt to config/config.txt, then uncomment CENTRAL_SQL_ENABLED and set CENTRAL_SERVER_ID." -ForegroundColor Yellow
}

# ── Done ─────────────────────────────────────────────────────────────────────

Write-Host ""
Write-Host "Central database setup complete!" -ForegroundColor Green
Write-Host "  Start          : scripts\central\db_central_start.ps1"
Write-Host "  Stop           : scripts\central\db_central_stop.ps1"
Write-Host "  Apply schema   : scripts\central\db_central_update.ps1"
Write-Host "  Authorize a server : scripts\central\db_central_add_server.ps1 -ServerId <name>"
Write-Host "  Revoke a server     : scripts\central\db_central_remove_server.ps1 -ServerId <name>"
Write-Host ""
Write-Host "This machine's own game server does NOT use this database until you set" -ForegroundColor DarkGray
Write-Host "CENTRAL_SERVER_ID in config.txt and put a RUNTIME login (not this admin one)" -ForegroundColor DarkGray
Write-Host "in config\central_dbconfig.txt -- db_central_add_server.ps1 prints one." -ForegroundColor DarkGray
