CREATE TABLE IF NOT EXISTS `ss13_mob_position` (
  `ckey`      VARCHAR(32)    NOT NULL,
  `char_name` VARCHAR(64)    NOT NULL,
  `x`         SMALLINT UNSIGNED NOT NULL,
  `y`         SMALLINT UNSIGNED NOT NULL,
  `z`         SMALLINT UNSIGNED NOT NULL,
  `saved_at`  TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ckey`, `char_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
