ALTER TABLE `ss13_mob_position`
  ADD COLUMN IF NOT EXISTS `in_lace`      TINYINT(1)     NOT NULL DEFAULT 0 AFTER `z`,
  ADD COLUMN IF NOT EXISTS `lace_pod_x`   SMALLINT UNSIGNED DEFAULT NULL AFTER `in_lace`,
  ADD COLUMN IF NOT EXISTS `lace_pod_y`   SMALLINT UNSIGNED DEFAULT NULL AFTER `lace_pod_x`,
  ADD COLUMN IF NOT EXISTS `lace_pod_z`   SMALLINT UNSIGNED DEFAULT NULL AFTER `lace_pod_y`;
