ALTER TABLE `ss13_mob_position`
  ADD COLUMN IF NOT EXISTS `last_pod_x` SMALLINT UNSIGNED DEFAULT NULL AFTER `char_state`,
  ADD COLUMN IF NOT EXISTS `last_pod_y` SMALLINT UNSIGNED DEFAULT NULL AFTER `last_pod_x`,
  ADD COLUMN IF NOT EXISTS `last_pod_z` SMALLINT UNSIGNED DEFAULT NULL AFTER `last_pod_y`;
