CREATE TABLE IF NOT EXISTS `ss13_join_whitelist` (
  `ckey`     VARCHAR(32) NOT NULL,
  `added_by` VARCHAR(32) DEFAULT NULL,
  `added_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ckey`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
