// AUTO-GENERATED by scripts/voicegen/build_bookended_lines.py -- do not hand-edit.
// Deciseconds via the SECONDS macro, each duration rounded up to the
// nearest tenth of a second -- consumed by play_announcer_sound()
// (code/defines/procs/announce.dm) to know when to advance the
// per-client announcer queue.
GLOBAL_LIST_INIT(announcer_sound_durations, list(
	"sound/AI/announcements/autosave_in_progress.ogg" = 4.4 SECONDS,
	"sound/AI/announcements/zone_highsec.ogg" = 4.5 SECONDS,
	"sound/AI/announcements/zone_medsec.ogg" = 4.7 SECONDS,
	"sound/AI/announcements/zone_nullsec.ogg" = 4.5 SECONDS,
	"sound/AI/announcements/raiding_allowed.ogg" = 4.4 SECONDS,
	"sound/AI/announcements/raiding_prohibited.ogg" = 4.5 SECONDS,
	"sound/AI/announcements/engines_powered_on.ogg" = 4.1 SECONDS,
	"sound/AI/announcements/engines_powered_off.ogg" = 4.2 SECONDS
))
