"""
Rebuilds the AI announcement voice lines from user-provided source
recordings in D:\\Downloads, replacing the pyttsx3 placeholders generated by
generate_ai_lines.py. No rumble bookend -- just the voice line, run through
an intensified, more cavernous "sci-fi" reverb.

Requires: pip install pedalboard
Also requires ffmpeg on PATH.
"""

import math
import pathlib
import subprocess
import tempfile

import numpy as np
from pedalboard import Pedalboard, Reverb
from pedalboard.io import AudioFile

SOURCE_DIR = pathlib.Path(r"D:\Downloads")
REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
OUTPUT_DIR = REPO_ROOT / "sound" / "AI" / "announcements"
DURATIONS_DM_PATH = REPO_ROOT / "code" / "defines" / "procs" / "_announcer_sound_durations.dm"
TARGET_SAMPLE_RATE = 16000
# How much trailing silence to give the reverb tail room to decay into --
# without this the wet tail gets hard-cut at the end of the dry buffer
# instead of ringing out naturally.
REVERB_TAIL_SECONDS = 2.5
FADE_OUT_SECONDS = 1.5

LINES = [
    "autosave_in_progress",
    "zone_highsec",
    "zone_medsec",
    "zone_nullsec",
    "raiding_allowed",
    "raiding_prohibited",
    "engines_powered_on",
    "engines_powered_off",
]

# Pushed well past sound/AI/Voice how-to.txt's documented Audacity chain --
# bigger room, more wet signal, and low damping so the tail rings out
# bright and long instead of getting absorbed, for a more cavernous,
# spacey "sci-fi comms" character rather than a subtle room tone. Backed off
# slightly from an initial pass that was too intense.
REVERB = Reverb(
    room_size=0.85,
    damping=0.25,
    wet_level=0.5,
    dry_level=0.5,
    width=0.8,
)


def resample_mono(src: pathlib.Path, dst: pathlib.Path, rate: int) -> None:
    subprocess.run(
        ["ffmpeg", "-y", "-i", str(src), "-ac", "1", "-ar", str(rate), str(dst)],
        check=True, capture_output=True,
    )


def apply_reverb(src: pathlib.Path, dst: pathlib.Path) -> None:
    board = Pedalboard([REVERB])
    with AudioFile(str(src)) as f:
        audio = f.read(f.frames)
        samplerate = f.samplerate
    # Pad trailing silence before processing so the wet tail has room to
    # decay into instead of getting hard-cut at the end of the dry signal.
    pad_samples = int(REVERB_TAIL_SECONDS * samplerate)
    padding = np.zeros((audio.shape[0], pad_samples), dtype=audio.dtype)
    padded = np.concatenate([audio, padding], axis=1)
    processed = board(padded, samplerate)
    with AudioFile(str(dst), "w", samplerate, processed.shape[0]) as f:
        f.write(processed)


def probe_duration_seconds(path: pathlib.Path) -> float:
    result = subprocess.run(
        ["ffprobe", "-v", "error", "-show_entries", "format=duration",
         "-of", "default=noprint_wrappers=1:nokey=1", str(path)],
        check=True, capture_output=True, text=True,
    )
    return float(result.stdout.strip())


def write_durations_manifest(durations: dict) -> None:
    lines = [
        "// AUTO-GENERATED by scripts/voicegen/build_bookended_lines.py -- do not hand-edit.",
        "// Deciseconds via the SECONDS macro, each duration rounded up to the",
        "// nearest tenth of a second -- consumed by play_announcer_sound()",
        "// (code/defines/procs/announce.dm) to know when to advance the",
        "// per-client announcer queue.",
        "GLOBAL_LIST_INIT(announcer_sound_durations, list(",
    ]
    entries = []
    for name, seconds in durations.items():
        rounded = math.ceil(seconds * 10) / 10
        entries.append(f'\t"sound/AI/announcements/{name}.ogg" = {rounded} SECONDS')
    lines.append(",\n".join(entries))
    lines.append("))")
    DURATIONS_DM_PATH.write_text("\n".join(lines) + "\n")


def encode_ogg(src: pathlib.Path, dst: pathlib.Path) -> None:
    # Belt-and-suspenders smooth fade over the last FADE_OUT_SECONDS,
    # regardless of total length -- reverse, fade-in (now at the true end),
    # reverse back -- so there's no residual click/step even if some
    # reverb energy is still audible when the padded tail runs out.
    subprocess.run(
        ["ffmpeg", "-y", "-i", str(src),
         "-af", f"areverse,afade=t=in:d={FADE_OUT_SECONDS},areverse",
         "-c:a", "libvorbis", "-q:a", "10", str(dst)],
        check=True, capture_output=True,
    )


def main() -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    durations = {}

    with tempfile.TemporaryDirectory() as tmp:
        tmp_dir = pathlib.Path(tmp)

        for name in LINES:
            src_mp3 = SOURCE_DIR / f"{name}.mp3"
            if not src_mp3.exists():
                raise SystemExit(f"Missing source recording: {src_mp3}")

            voice_resampled = tmp_dir / f"{name}_resampled.wav"
            voice_reverb = tmp_dir / f"{name}_reverb.wav"
            final_ogg = OUTPUT_DIR / f"{name}.ogg"

            print(f"Processing: {name}")
            resample_mono(src_mp3, voice_resampled, TARGET_SAMPLE_RATE)
            apply_reverb(voice_resampled, voice_reverb)
            encode_ogg(voice_reverb, final_ogg)
            durations[name] = probe_duration_seconds(final_ogg)
            print(f"  wrote {final_ogg} ({durations[name]:.2f}s)")

    write_durations_manifest(durations)
    print(f"Wrote duration manifest: {DURATIONS_DM_PATH}")
    print("Done.")


if __name__ == "__main__":
    main()
