"""
One-off companion to build_bookended_lines.py for the tractor beam + lobby
welcome voice line batch. Same resample -> reverb -> OGG treatment and the
same duration-manifest bookkeeping, but MERGES its new entries into the
existing _announcer_sound_durations.dm instead of overwriting the whole
file -- build_bookended_lines.py's own LINES list expects all 28 of the
original source recordings to still be sitting in D:\\Downloads together,
which is no longer true (most have already been consumed by an earlier
run), so re-running it as-is would either abort outright or, worse, wipe
the duration entries for every already-shipped line that isn't re-processed
in the same pass.

Requires: pip install pedalboard
Also requires ffmpeg on PATH.
"""

import math
import pathlib
import re
import subprocess
import tempfile

import numpy as np
from pedalboard import Pedalboard, Reverb
from pedalboard.io import AudioFile

SOURCE_DIR = pathlib.Path(r"D:\Downloads")
REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
OUTPUT_DIR = REPO_ROOT / "sound" / "AI" / "announcements"
DURATIONS_DM_PATH = REPO_ROOT / "code" / "defines" / "procs" / "_announcer_sound_durations.dm"
TARGET_SAMPLE_RATE = 16000
REVERB_TAIL_SECONDS = 2.5
FADE_OUT_SECONDS = 1.5

# (source .mp3 stem in D:\Downloads, destination .ogg stem in sound/AI/announcements)
LINES = [
    ("TRACTOR_BEAM_ENGAGED", "tractor_beam_engaged"),
    ("ENEMY_TRACTOR_BEAM_ENGAGED", "enemy_tractor_beam_engaged"),
    ("TRACTOR_BEAM_DISENGAGED", "tractor_beam_released"),
    ("ENEMY_TRACTOR_BEAM_HAS_RELEASED", "enemy_tractor_beam_released"),
    ("TRACTOR_BEAM_ESCAPE_SUCCESS", "tractor_beam_escape_success"),
    ("TRACTOR_BEAM_ESCAPE_FAILED", "tractor_beam_escape_failed"),
    ("ENEMY_ESCAPE_SUCCESS", "enemy_escape_success"),
    ("ENEMY_ESCAPE_FAILED", "enemy_escape_failed"),
    ("WELCOME_TO_FRONTIER_STATION", "welcome_to_frontier_station"),
    ("WELCOME_BACK", "welcome_back"),
]

REVERB = Reverb(
    room_size=0.85,
    damping=0.25,
    wet_level=0.5,
    dry_level=0.5,
    width=0.8,
)


def resample_mono(src: pathlib.Path, dst: pathlib.Path, rate: int) -> None:
    subprocess.run(
        ["ffmpeg", "-y", "-i", str(src), "-ac", "1", "-ar", str(rate), str(dst)],
        check=True, capture_output=True,
    )


def apply_reverb(src: pathlib.Path, dst: pathlib.Path) -> None:
    board = Pedalboard([REVERB])
    with AudioFile(str(src)) as f:
        audio = f.read(f.frames)
        samplerate = f.samplerate
    pad_samples = int(REVERB_TAIL_SECONDS * samplerate)
    padding = np.zeros((audio.shape[0], pad_samples), dtype=audio.dtype)
    padded = np.concatenate([audio, padding], axis=1)
    processed = board(padded, samplerate)
    with AudioFile(str(dst), "w", samplerate, processed.shape[0]) as f:
        f.write(processed)


def probe_duration_seconds(path: pathlib.Path) -> float:
    result = subprocess.run(
        ["ffprobe", "-v", "error", "-show_entries", "format=duration",
         "-of", "default=noprint_wrappers=1:nokey=1", str(path)],
        check=True, capture_output=True, text=True,
    )
    return float(result.stdout.strip())


def encode_ogg(src: pathlib.Path, dst: pathlib.Path) -> None:
    subprocess.run(
        ["ffmpeg", "-y", "-i", str(src),
         "-af", f"areverse,afade=t=in:d={FADE_OUT_SECONDS},areverse",
         "-c:a", "libvorbis", "-q:a", "10", str(dst)],
        check=True, capture_output=True,
    )


def read_existing_manifest() -> "dict[str, str]":
    """Parses the current _announcer_sound_durations.dm into an ordered
    {path: raw_duration_expr} dict, preserving the exact existing text for
    every entry we're not touching (so untouched lines are byte-identical
    after the merge, not just numerically equivalent)."""
    text = DURATIONS_DM_PATH.read_text()
    entries = {}
    for match in re.finditer(r'"(sound/AI/announcements/[^"]+\.ogg)"\s*=\s*([\d.]+ SECONDS)', text):
        entries[match.group(1)] = match.group(2)
    return entries


def write_merged_manifest(existing: "dict[str, str]", new_durations: dict) -> None:
    merged = dict(existing)
    for name, seconds in new_durations.items():
        rounded = math.ceil(seconds * 10) / 10
        merged[f"sound/AI/announcements/{name}.ogg"] = f"{rounded} SECONDS"

    lines = [
        "// AUTO-GENERATED by scripts/voicegen/build_bookended_lines.py -- do not hand-edit.",
        "// Deciseconds via the SECONDS macro, each duration rounded up to the",
        "// nearest tenth of a second -- consumed by play_announcer_sound()",
        "// (code/defines/procs/announce.dm) to know when to advance the",
        "// per-client announcer queue.",
        "GLOBAL_LIST_INIT(announcer_sound_durations, list(",
    ]
    entries = [f'\t"{path}" = {expr}' for path, expr in merged.items()]
    lines.append(",\n".join(entries))
    lines.append("))")
    DURATIONS_DM_PATH.write_text("\n".join(lines) + "\n")


def main() -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    existing = read_existing_manifest()
    print(f"Existing manifest entries: {len(existing)}")

    durations = {}
    with tempfile.TemporaryDirectory() as tmp:
        tmp_dir = pathlib.Path(tmp)

        for source_stem, dest_stem in LINES:
            src_mp3 = SOURCE_DIR / f"{source_stem}.mp3"
            if not src_mp3.exists():
                raise SystemExit(f"Missing source recording: {src_mp3}")

            voice_resampled = tmp_dir / f"{dest_stem}_resampled.wav"
            voice_reverb = tmp_dir / f"{dest_stem}_reverb.wav"
            final_ogg = OUTPUT_DIR / f"{dest_stem}.ogg"

            print(f"Processing: {source_stem} -> {dest_stem}.ogg")
            resample_mono(src_mp3, voice_resampled, TARGET_SAMPLE_RATE)
            apply_reverb(voice_resampled, voice_reverb)
            encode_ogg(voice_reverb, final_ogg)
            durations[dest_stem] = probe_duration_seconds(final_ogg)
            print(f"  wrote {final_ogg} ({durations[dest_stem]:.2f}s)")

    write_merged_manifest(existing, durations)
    print(f"Merged {len(durations)} new entries into: {DURATIONS_DM_PATH}")
    print("Done.")


if __name__ == "__main__":
    main()
