<#
.SYNOPSIS
    One-time setup: starts the MariaDB container and applies all SQL migrations via Flyway.
    Safe to re-run -- Flyway only applies migrations that have not been applied yet.
    Compatible with Windows PowerShell 5.1+ and PowerShell 7+.

.PREREQUISITES
    Docker Desktop must be installed and running.
    https://www.docker.com/products/docker-desktop/
#>

$ErrorActionPreference = "Stop"

$Root = Split-Path $PSScriptRoot -Parent

# DB_PORT (.env, repo root) -- host port for the "db" container. Same file
# docker-compose.yml itself reads (${DB_PORT:-3306}) for the "db" service's
# port mapping, so this stays in sync with whatever the container actually
# publishes. Blank/missing .env or key -> default 3306.
$dbPort = "3306"
$envPath = Join-Path $Root ".env"
if (Test-Path $envPath) {
    foreach ($line in Get-Content $envPath) {
        if ($line -match '^\s*DB_PORT\s*=\s*(\S+)') {
            $dbPort = $Matches[1]
        }
    }
}

# ── 1. Verify Docker is available ────────────────────────────────────────────

Write-Host "Checking Docker..." -ForegroundColor Cyan
try {
    docker info 2>&1 | Out-Null
} catch {
    Write-Error "Docker is not running or not installed. Install Docker Desktop and start it, then re-run this script."
    exit 1
}
Write-Host "Docker OK." -ForegroundColor Green

# ── 2. Start the database container ──────────────────────────────────────────

Write-Host "`nStarting MariaDB container..." -ForegroundColor Cyan
Set-Location $Root
docker compose up -d db

# ── 3. Wait for MariaDB to accept connections (up to 60 s) ───────────────────

Write-Host "Waiting for MariaDB to be ready..." -ForegroundColor Cyan
$attempts = 0
$ready    = $false
while ($attempts -lt 30) {
    Start-Sleep -Seconds 2
    try {
        docker exec aurora-db mariadb-admin ping -u aurora -paurora 2>&1 | Out-Null
        if ($LASTEXITCODE -eq 0) {
            $ready = $true
            break
        }
    } catch {
        # Server not ready yet -- keep waiting
    }
    $attempts++
    Write-Host "  ...still waiting ($($attempts * 2)s)" -ForegroundColor DarkGray
}

if (-not $ready) {
    Write-Error "MariaDB did not become ready within 60 seconds. Check 'docker logs aurora-db'."
    exit 1
}
Write-Host "MariaDB is ready." -ForegroundColor Green

# ── 4. Run Flyway migrations ──────────────────────────────────────────────────

Write-Host "`nRunning Flyway migrations..." -ForegroundColor Cyan

$sqlPath = Join-Path $Root "SQL\migrate-2023"

docker run --rm `
    --network host `
    -v "${sqlPath}:/flyway/sql" `
    flyway/flyway:10 `
    -url="jdbc:mariadb://localhost:$dbPort/aurora_persist" `
    -user=aurora `
    -password=aurora `
    -table=schema_version_2023 `
    migrate

if ($LASTEXITCODE -ne 0) {
    Write-Error "Flyway migration failed. Check output above."
    exit 1
}
Write-Host "Migrations applied." -ForegroundColor Green

# ── 5. Write config/dbconfig.txt ─────────────────────────────────────────────

Write-Host "`nWriting config/dbconfig.txt..." -ForegroundColor Cyan
$configDir = Join-Path $Root "config"
if (-not (Test-Path $configDir)) {
    New-Item -ItemType Directory $configDir | Out-Null
}

$dbconfigLines = @(
    "# MySQL Connection Configuration -- generated by db_setup.ps1",
    "",
    "ADDRESS localhost",
    "PORT $dbPort",
    "DATABASE aurora_persist",
    "LOGIN aurora",
    "PASSWORD aurora"
)
Set-Content (Join-Path $configDir "dbconfig.txt") -Value $dbconfigLines -Encoding UTF8
Write-Host "dbconfig.txt written." -ForegroundColor Green

# ── 6. Enable SQL in config/config.txt ───────────────────────────────────────

$configTxt = Join-Path $configDir "config.txt"
if (Test-Path $configTxt) {
    Write-Host "Enabling SQL_ENABLED in config/config.txt..." -ForegroundColor Cyan
    $content = Get-Content $configTxt -Raw
    $updated = $content -replace '(?m)^#+\s*SQL_ENABLED', 'SQL_ENABLED'
    if ($updated -eq $content -and $content -notmatch '(?m)^SQL_ENABLED') {
        $updated = $content + "`nSQL_ENABLED`n"
    }
    Set-Content $configTxt $updated -Encoding UTF8
    Write-Host "SQL_ENABLED set." -ForegroundColor Green
} else {
    Write-Host "config/config.txt not found -- copy config/example/config.txt to config/config.txt and uncomment SQL_ENABLED." -ForegroundColor Yellow
}

# ── 7. Ensure backups directory exists ───────────────────────────────────────

$backupsDir = Join-Path $Root "backups"
if (-not (Test-Path $backupsDir)) {
    New-Item -ItemType Directory $backupsDir | Out-Null
}

# ── 8. Optional: register daily backup scheduled task (Windows only) ─────────
# Register-ScheduledTask is a Windows Task Scheduler cmdlet with no PowerShell
# Core equivalent on Linux/macOS -- asking the question there would just lead
# into a crash if answered yes, so skip it outright on non-Windows and point
# at cron/systemd instead. $IsWindows is a PowerShell Core automatic variable.

if ($IsWindows -or $PSVersionTable.PSEdition -eq 'Desktop') {
    Write-Host ""
    $schedule = Read-Host "Register a Windows Scheduled Task to back up the DB daily at 04:00? (y/N)"
    if ($schedule -match '^[Yy]') {
        $backupScript = Join-Path $PSScriptRoot "db_backup.ps1"
        $taskArg = '-NonInteractive -File "' + $backupScript + '"'
        $action   = New-ScheduledTaskAction -Execute "pwsh.exe" -Argument $taskArg
        $trigger  = New-ScheduledTaskTrigger -Daily -At "04:00"
        $settings = New-ScheduledTaskSettingsSet -StartWhenAvailable
        Register-ScheduledTask -TaskName "AuroraDB_DailyBackup" -Action $action -Trigger $trigger -Settings $settings -RunLevel Highest -Force | Out-Null
        Write-Host "Scheduled task 'AuroraDB_DailyBackup' registered." -ForegroundColor Green
    }
} else {
    Write-Host ""
    Write-Host "Scheduled-task auto-backups are Windows-only -- on this platform, schedule scripts/db_backup.sh yourself (cron or a systemd timer)." -ForegroundColor Yellow
}

# ── Done ─────────────────────────────────────────────────────────────────────

Write-Host ""
Write-Host "Setup complete!" -ForegroundColor Green
Write-Host "  Start DB   : scripts\db_start.ps1"
Write-Host "  Stop DB    : scripts\db_stop.ps1"
Write-Host "  Restart DB : scripts\db_restart.ps1 (force-recreate; fixes stuck ports, applies a new DB_PORT)"
Write-Host "  Backup     : scripts\db_backup.ps1"
