#!/bin/sh
# One-time setup: starts the MariaDB container and applies all SQL migrations via Flyway.
# Safe to re-run -- Flyway only applies migrations that have not been applied yet.
# Native translation of db_setup.ps1 -- no PowerShell dependency.
#
# PREREQUISITES: Docker must be installed and running.

set -eu

ROOT="$(cd "$(dirname "$0")/.." && pwd)"

# ── 1. Verify Docker is available ────────────────────────────────────────────

echo "Checking Docker..."
if ! docker info > /dev/null 2>&1; then
	echo "Docker is not running or not installed. Install Docker and start it, then re-run this script." >&2
	exit 1
fi
echo "Docker OK."

# ── 2. Start the database container ──────────────────────────────────────────

echo ""
echo "Starting MariaDB container..."
cd "$ROOT"
docker compose up -d db

# ── 3. Wait for MariaDB to accept connections (up to 60 s) ───────────────────

echo "Waiting for MariaDB to be ready..."
ATTEMPTS=0
READY=0
while [ "$ATTEMPTS" -lt 30 ]; do
	sleep 2
	if docker exec aurora-db mariadb-admin ping -u aurora -paurora > /dev/null 2>&1; then
		READY=1
		break
	fi
	ATTEMPTS=$((ATTEMPTS + 1))
	echo "  ...still waiting ($((ATTEMPTS * 2))s)"
done

if [ "$READY" -ne 1 ]; then
	echo "MariaDB did not become ready within 60 seconds. Check 'docker logs aurora-db'." >&2
	exit 1
fi
echo "MariaDB is ready."

# ── 4. Run Flyway migrations ──────────────────────────────────────────────────

echo ""
echo "Running Flyway migrations..."

SQL_PATH="$ROOT/SQL/migrate-2023"

docker run --rm \
	--network host \
	-v "$SQL_PATH:/flyway/sql" \
	flyway/flyway:10 \
	-url="jdbc:mariadb://localhost:3306/aurora_persist" \
	-user=aurora \
	-password=aurora \
	-table=schema_version_2023 \
	migrate

echo "Migrations applied."

# ── 5. Write config/dbconfig.txt ─────────────────────────────────────────────

echo ""
echo "Writing config/dbconfig.txt..."
CONFIG_DIR="$ROOT/config"
mkdir -p "$CONFIG_DIR"

cat > "$CONFIG_DIR/dbconfig.txt" <<'EOF'
# MySQL Connection Configuration -- generated by db_setup.sh

ADDRESS localhost
PORT 3306
DATABASE aurora_persist
LOGIN aurora
PASSWORD aurora
EOF
echo "dbconfig.txt written."

# ── 6. Enable SQL in config/config.txt ───────────────────────────────────────

CONFIG_TXT="$CONFIG_DIR/config.txt"
if [ -f "$CONFIG_TXT" ]; then
	echo "Enabling SQL_ENABLED in config/config.txt..."
	if grep -q '^SQL_ENABLED' "$CONFIG_TXT"; then
		: # already enabled
	elif grep -q '^#\+[[:space:]]*SQL_ENABLED' "$CONFIG_TXT"; then
		sed -i.bak -E 's/^#+[[:space:]]*SQL_ENABLED/SQL_ENABLED/' "$CONFIG_TXT" && rm -f "$CONFIG_TXT.bak"
	else
		printf '\nSQL_ENABLED\n' >> "$CONFIG_TXT"
	fi
	echo "SQL_ENABLED set."
else
	echo "config/config.txt not found -- copy config/example/config.txt to config/config.txt and uncomment SQL_ENABLED."
fi

# ── 7. Ensure backups directory exists ───────────────────────────────────────

mkdir -p "$ROOT/backups"

# ── 8. Daily backup scheduling (cron, not a Windows Scheduled Task) ──────────

echo ""
echo "To schedule daily backups at 04:00, add this to your crontab (crontab -e):"
echo "  0 4 * * * $ROOT/scripts/db_backup.sh >> $ROOT/backups/backup_cron.log 2>&1"

# ── Done ─────────────────────────────────────────────────────────────────────

echo ""
echo "Setup complete!"
echo "  Start DB : scripts/db_start.sh"
echo "  Stop DB  : scripts/db_stop.sh"
echo "  Backup   : scripts/db_backup.sh"
